use strict;
use warnings;
use Test::More;

# META.yml/META.json are generated by `make dist` and only exist inside the
# tarball, not in the source tree, so exclude the file-existence checks for
# those when running author tests against source.
eval q{
    use Test::Kwalitee::Extra
        qw(!has_meta_yml !has_meta_json !has_separate_license_file !prereq_matches_use);
};
plan skip_all => 'Test::Kwalitee::Extra required' if $@;
